### ISSUE TITLE
Windows requires admin rights for creating symlinks

### ISSUE THREAD

**Issue by marcelklehr** [kevva/decompress#41]
I know. It sucks, but this line doesn't work when you're not running node as admin on windows: https://github.com/kevva/decompress/blob/master/index.js#L61

 Is it possible to somehow just copy the linked file?

**Comment by marcelklehr** [comment]
It appears hard links don't require admin rights: https://github.com/npm/fstream/blob/master/lib/link-writer.js#L34

**Comment by kevva** [comment]
@marcelklehr, could you try running from `master` and see if that fixes your issue?

**Comment by Skn0tt** [comment]
Hey folks! I've hit an issue that I believe is related to this. Given a ZIP that contains a directory symlink, `decompress` on Windows will try recreating it as a hardlink. This will fail, because hardlinks don't support linking between directories. Symlinks do, though!

What do you think about only using hardlinks as a fallback if the symlink fails, e.g. because of missing admin permissions?
Kinda like this:

```js
if (x.type === 'symlink') {
	return fsP.symlink(x.linkname, dest).catch((err) => {
             if (process.platform === 'win32' && err is because of missing admin permissions) {
                 fsP.link(dest, path.join(dest, "..", x.linkname))
             }
             throw err
        });
}
```
Happy to provide a PR if you think something like this is viable.
