### ISSUE TITLE
Vulnerable to zip slip

### ISSUE THREAD

**Issue by magicOz** [kevva/decompress#71]
It appears as **decompress** is vulnerable to archives containing files that hold path-traversal names such as `../../outside.txt`.

As a PoC I have attached a .tar.gz-archive([slip.tar.gz](https://github.com/kevva/decompress/files/3689365/slip.tar.gz)) that will, when extracted, create a file in `/tmp/slipped.txt`.
Use the example code to extract:
```javascript
const decompress = require('decompress');

decompress('slip.tar.gz', 'dist').then(files => {
	console.log('done!');
});
```
Note that this will not work out-of-the-box with .zip-archives since `yauzl` will throw an exception if the entry's filename contains "`..`".

However, since this package also supports symlinks we can use that instead to bypass this limitation.
But just adding a symlink to our desired target location won't do the trick - since the archive's files are being extracted asynchronous ([index.js#44-73](https://github.com/kevva/decompress/blob/master/index.js#L44,L73)) we will end up in a race condition between extracting the symlink and the file referencing it.

By creating a directory and within that create a symlink to its' parent directory. Continue with creating a symlink to `/` and a file with a name using a looped structure of all symlinks to the target. We end up with something like;
```bash
mkdir generic_dir
ln -s ../ generic_dir/symlink_to_parent_dir
ln -s / symlink_to_root
touch generic_dir/symlink_to_parent_dir/generic_dir/symlink_to_parent_dir/[...]/symlink_to_root/tmp/slipped_zip.txt
```
Adding this to an archive allows us to always win the race!
Here's a PoC 
([slip.zip](https://github.com/kevva/decompress/files/4259380/slip.zip)), that when extracted will create a file in `/tmp/slipped_zip.txt`. Demonstrating how this also works for zip-archives using symlinks.

**Comment by metacoding** [comment]
Now 'npm audit' warns this vulnerability as a high risk one. I am using filePond in my React app and because FilePond is dependent to this package I got 9 High Risk vulnerabilities and none of them can be solved because there is no patch available yet. Please somebody how knows this package, submit a fix.

![image](https://user-images.githubusercontent.com/16768266/75398694-4d463c80-58f2-11ea-97d4-d0653ccc18c8.png)

**Comment by rajbir123** [comment]
what is the alternative solution for this decompress? any other library?

**Comment by jdillick** [comment]
NPM security needs to get a grip. This isn't a security problem. Does this bypass filesystem security? Nope.

**Comment by Saeger** [comment]
> NPM security needs to get a grip. This isn't a security problem. Does this bypass filesystem security? Nope. i.e. every file in an archive is an "arbitrary file".

Maybe you could right somewhere or to some application that could execute that file or cause errors to applications. In my opinion this isn't minor either.

**Comment by Eyas** [comment]
> NPM security needs to get a grip. This isn't a security problem. Does this bypass filesystem security? Nope. i.e. every file in an archive is an "arbitrary file".

The problem isn't that the files are arbitrary, it's that unpacking an archive can result in files writing to arbitrary paths. So if you unpack to `/tmp/foo` a malicious .tar.gz can trick this library into outputing a file to `/usr/bin` instead, etc.

Definitely a security risk.

**Comment by XhmikosR** [comment]
@kevva @sindresorhus are you guys aware of this?

**Comment by sr1ch1** [comment]
The issue alone is not a security problem. But it opens the door for security issues as many packages depend on this one. I had a look at this issue and found out that it originates in the package decompress-tar. 
I fixed it there and created a [pull request](https://github.com/kevva/decompress-tar/pull/12). The build has broken due to the old project setup. @kevva should decide how to proceed. I will support if necessary.

**Comment by jdillick** [comment]
> > NPM security needs to get a grip. This isn't a security problem. Does this bypass filesystem security? Nope. i.e. every file in an archive is an "arbitrary file".
> 
> The problem isn't that the files are arbitrary, it's that unpacking an archive can result in files writing to arbitrary paths. So if you unpack to `/tmp/foo` a malicious .tar.gz can trick this library into outputing a file to `/usr/bin` instead, etc.
> 
> Definitely a security risk.

Nah. Only if you are doing something insane like running node as root. Again, you can only right to the filesystem if you have permission. `/tmp/foo` isn't a problem. Only if you springboard off another vulnerability can you make anything of this so called "high" security risk.

`tar -xzvf my.tar.gz` isn't considered insecure if if does what you ask, i.e. unpack the files (with all the arbitrary paths inside) into your filesystem. If I execute this with sudo, now we have a problem. If I execute as an ordinary user, it's gonna fail to write to `/usr/bin`, just like decompress will.

**Comment by jdillick** [comment]
> > > NPM security needs to get a grip. This isn't a security problem. Does this bypass filesystem security? Nope. i.e. every file in an archive is an "arbitrary file".

After some investigation of the behavior of the command line utilities (and notwithstanding NPM security group's habitual and lazy scarlet-lettering of packages), I recant my objection on the grounds that this is a bug for other reasons.

Looks like BSD tar (such as in Darwin) does allow `..` prefixes during creation, but requires the `-P` (preserves paths) flag to unpack them. Linux (GNU tar) strips `../` during tar creation, always. Therefore, in practice parent relative paths should be rather rare, and the ordinary behavior would be to not expect them exist in the archive, or would otherwise expect them to be ignored by default.

I think the Linux behavior of treated `../foo/` as `foo/` would at least be expected.

Workaround with current behavior to correct this behavior might be:

```
const decompress = require('decompress');
const path = require('path');
const assert = require('assert');

const fixPath = (file, targetDir) => {
  // resolve relative path to target. e.g. file.path of a/../../b could actually be ../b
  const resolvedRelative = path.relative(targetDir, path.resolve(targetDir, file.path));

  // get rid of any .. prefix
  const fixed = resolvedRelative.replace(/^(\.\.[/\\\\]?)+/, '');
  file.path = fixed;
  return file;
};

assert.deepEqual(fixPath({ path: '../bar'}, './foo'), { path: 'bar' });
assert.deepEqual(fixPath({ path: '../../bar'}, './foo'), { path: 'bar' });
assert.deepEqual(fixPath({ path: 'bar/../../baz'}, './foo'), { path: 'baz' })

const targetDir = path.resolve('./test-dir');

// foo.tgz has:
// ../
// ../baz/
// ../bar/
// ../bar/text.txt
// ../baz/text.txt

decompress('./foo.tgz', targetDir, {
  map: file => {
    file = fixPath(file, targetDir);
    return file;
  },
  filter: file => {
    // strip empty directory creation
    file = fixPath(file, targetDir);
    return file.path.length;
  },
})
.then(files => {
  files.forEach(file => console.log(file.path))
});
// Outputs:
// baz/
// bar/
// bar/text.txt
// baz/text.txt

```

**Comment by dl748** [comment]
> Nah. Only if you are doing something insane like running node as root on a web service, and using it to unpack user provided tarballs. Again, you can only write to the filesystem if you have permission. `/tmp/foo` isn't a problem. Only if you springboard off another vulnerability can you make anything of this so called "high" security risk.

Yes, this is very much a security risk.  Running code as root is not a vulnerability in itself, its just not preferred practice if you can help it.  It could be something as simple as automated script.  There are still a lot of things only root can do.  Linux has been doing a better jobs about giving privileges to non root user but there are still several things that require root access. Not to mention there are still several system that require root access for something as simple as running on any port under 1024.

It might even be something more insidious like having ~/.node_modules in the path.  Where it installs a local module that could overwrite modules a lot people install globally, like npm or webpack.

Code by default should be secure, WITH the possible option of bypassing and warning the developer of possible issues.  Most *nix archivers (e.g. tar/zip) do not allow extraction outside of the specified directory (think root for that dir) unless you specify a specific option to allow files outside of it.

**Comment by jdillick** [comment]
> > Nah. Only if you are doing something insane like running node as root on a web service, and using it to unpack user provided tarballs. Again, you can only write to the filesystem if you have permission. `/tmp/foo` isn't a problem. Only if you springboard off another vulnerability can you make anything of this so called "high" security risk.
> 
> Yes, this is very much a security risk. Running code as root is not a vulnerability in itself, its just not preferred practice if you can help it. It could be something as simple as automated script. There are still a lot of things only root can do. Linux has been doing a better jobs about giving privileges to non root user but there are still several things that require root access. Not to mention there are still several system that require root access for something as simple as running on any port under 1024.
> 
> It might even be something more insidious like having ~/.node_modules in the path. Where it installs a local module that could overwrite modules a lot people install globally, like npm or webpack.
> 
> Code by default should be secure, WITH the possible option of bypassing and warning the developer of possible issues. Most *nix archivers (e.g. tar/zip) do not allow extraction outside of the specified directory (think root for that dir) unless you specify a specific option to allow files outside of it.
> 
> unzip requires -: -> https://linux.die.net/man/1/unzip `` "For security reasons, unzip normally removes ``parent dir'' path components (``../'')" ``
> tar requires -P -> https://linux.die.net/man/1/tar

If a sys admin or coder requires continuously running your node app as root to get ports below 1024 (or any other privileged system activity), frankly they are not competent to be writing/running web services. Sure, in the most naive setups you may need to use root in some capacity to "initiate" a service, but you would never maintain that webservice acting under the powers of root under normal operating circumstances, you would perform what needed to be done with privilege and then you would de-escalate your privileges, with `process.setuid(id)`, or daemonize your server, use pm2/spawn new low priv processes, use docker, use a proxy, etc. Sorry, if some can't see how running your webservice process as root user is far more dangerous than having a utility that walks a variable list of relative paths and performing writes, then I have no words.

`tar -xzvPf  ~/foo.tgz` doesn't require -P for "security reasons", it's a matter of practicality because you can execute the extraction anywhere, parent relative paths can easily become meaningless / nonsensical.

Also, you kinda missed the point. We don't nerf functionality in a language or "utility function" simply because it can be used badly. `fs.writeFile()` can be used badly, indeed it can write to arbitrary paths! Frankly, the original authors of this package should be commended for adding the map and filter options, making this an excellent choice for people wanting to extract archives securely, and with expected results. That being said, I've already withdrawn my objection on the grounds that I think the default behavior is indeed a bug, but ya'll need to remember that code like this is used in more circumstances than web services (such as command line utilities).

Again, "may cause a security consequences" and "no way to avoid security consequences" are different levels of risk, and the current behavior falls squarely in the former classification. Not high.

**Comment by dl748** [comment]
> If a sys admin or coder requires continuously running your node app as root to get ports below 1024 (or any other privileged system activity), frankly they are not competent to be writing/running web services. Sure, in the most naive setups you may need to use root in some capacity to "initiate" a service, but you would never maintain that webservice acting under the powers of root under normal operating circumstances, you would perform what needed to be done with privilege and then you would de-escalate your privileges, with `process.setuid(id)`, or daemonize your server, use pm2/spawn new low priv processes, use docker, use a proxy, etc. Sorry, if some can't see how running your webservice process as root user is far more dangerous than having a utility that walks a variable list of relative paths and performing writes, then I have no words.
> 

That was a for instance, but it could be as simple is to access files that only root has access to, and only root SHOULD have access to.  Saying you can't write code in NodeJS for root because it has unintended side-affected security issues is a terrible excuse.

> `tar -xzvPf ~/foo.tgz` doesn't require -P for "security reasons", it's a matter of practicality because you can execute the extraction anywhere, parent relative paths can easily become meaningless / nonsensical.
> 

The REST of the world basically thought it was a security issue, which is why it got patched (https://nvd.nist.gov/vuln/detail/CVE-2001-1267).  Even if you don't think it was.  -P was added to tar when they stopped allowing absolute paths to change files (hackers were putting in /etc/passwd and /etc/shadow in the tar).  The problem was that they still allowed traversing outside of the extraction path which IS/WAS a security bug, and they patched it in 2001-08-27 (version 1.13.20)

```
        (extract_archive): Fix test for absolute pathnames and/or "..".
```

https://access.redhat.com/security/cve/cve-2001-1267
https://www.suse.com/security/cve/CVE-2001-1267/
https://www.tenable.com/cve/CVE-2001-1267

Now, this vulnerability, was marked as low, but the nodejs one is marked as high.  Not sure why they did that though. I personally don't think it warrants a high, maybe a medium at most.

I'm not sure if this code does it, but another issue in tar was the ability to create a symbolic link to an absolute path and then extract to that link, which they fixed as well.

> Also, you kinda missed the point. We don't nerf functionality in a language or "utility function" simply because it can be used badly. `fs.writeFile()` can be used badly, indeed it can write to arbitrary paths! Frankly, the original authors of this package should be commended for adding the map and filter options, making this an excellent choice for people wanting to extract archives securely, and with expected results. That being said, I've already withdrawn my objection on the grounds that I think the default behavior is indeed a bug, but ya'll need to remember that code like this is used in more circumstances than web services (such as command line utilities).

You do patch these issues even if it breaks(i think thats what you meant by "nerf") functionality because developers DON'T expect underlying code to have security problems. The default act of ANY "utitlity" should be SAFE/SECURE even if it breaks functionality.  If that functionality is still needed, then the developer should provide a way to EXPLICITLY bypass said security.  It should take effort to make things insecure because you are intentionally doing so, but it should not take effort to secure it.  Almost every utility in the past has done so, and the ones that didn't, people are not using anymore.

**Comment by jdillick** [comment]
> > If a sys admin or coder requires continuously running your node app as root to get ports below 1024 (or any other privileged system activity), frankly they are not competent to be writing/running web services. Sure, in the most naive setups you may need to use root in some capacity to "initiate" a service, but you would never maintain that webservice acting under the powers of root under normal operating circumstances, you would perform what needed to be done with privilege and then you would de-escalate your privileges, with `process.setuid(id)`, or daemonize your server, use pm2/spawn new low priv processes, use docker, use a proxy, etc. Sorry, if some can't see how running your webservice process as root user is far more dangerous than having a utility that walks a variable list of relative paths and performing writes, then I have no words.
> 
> That was a for instance, but it could be as simple is to access files that only root has access to, and only root SHOULD have access to. Saying you can't write code in NodeJS for root because it has unintended side-affected security issues is a terrible excuse.
> 
> > `tar -xzvPf ~/foo.tgz` doesn't require -P for "security reasons", it's a matter of practicality because you can execute the extraction anywhere, parent relative paths can easily become meaningless / nonsensical.
> 
> The REST of the world basically thought it was a security issue, which is why it got patched (https://nvd.nist.gov/vuln/detail/CVE-2001-1267). Even if you don't think it was. -P was added to tar when they stopped allowing absolute paths to change files (hackers were putting in /etc/passwd and /etc/shadow in the tar). The problem was that they still allowed traversing outside of the extraction path which IS/WAS a security bug, and they patched it in 2001-08-27 (version 1.13.20)
> 
> ```
>         (extract_archive): Fix test for absolute pathnames and/or "..".
> ```
> 
> https://access.redhat.com/security/cve/cve-2001-1267
> https://www.suse.com/security/cve/CVE-2001-1267/
> https://www.tenable.com/cve/CVE-2001-1267
> 
> Now, this vulnerability, was marked as low, but the nodejs one is marked as high. Not sure why they did that though. I personally don't think it warrants a high, maybe a medium at most.
> 
> I'm not sure if this code does it, but another issue in tar was the ability to create a symbolic link to an absolute path and then extract to that link, which they fixed as well.
> 
> > Also, you kinda missed the point. We don't nerf functionality in a language or "utility function" simply because it can be used badly. `fs.writeFile()` can be used badly, indeed it can write to arbitrary paths! Frankly, the original authors of this package should be commended for adding the map and filter options, making this an excellent choice for people wanting to extract archives securely, and with expected results. That being said, I've already withdrawn my objection on the grounds that I think the default behavior is indeed a bug, but ya'll need to remember that code like this is used in more circumstances than web services (such as command line utilities).
> 
> You do patch these issues even if it breaks(i think thats what you meant by "nerf") functionality because developers DON'T expect underlying code to have security problems. The default act of ANY "utitlity" should be SAFE/SECURE even if it breaks functionality. If that functionality is still needed, then the developer should provide a way to EXPLICITLY bypass said security. It should take effort to make things insecure because you are intentionally doing so, but it should not take effort to secure it. Almost every utility in the past has done so, and the ones that didn't, people are not using anymore.

So you are saying we should patch, `fs.writeFile()` to prevent it from writing to arbitrary files? Got it.

**Comment by dl748** [comment]
Umm no.  Wow, you went from completely right to completely left.  The people who patched tar, didn't tell the OS people to fix their code.  The utility allowed it to happen, so they fixed it.  When i tell tar/zip to extract an archive to a directoy, it shouldn't be expected that it'll change files outside of that directory.  Thats completely insane.  They require an option to say, "Yeah I want you to possibly do bad things here, but i'm giving you permission, because I know what I'm doing".  It shouldn't be any different here.

**Comment by jdillick** [comment]
> Umm no. Wow, you went from completely right to completely left. The people who patched tar, didn't tell the OS people to fix their code. The utility allowed it to happen, so they fixed it. When i tell tar/zip to extract an archive to a directoy, it shouldn't be expected that it'll change files outside of that directory. Thats completely insane. They require an option to say, "Yeah I want you to possibly do bad things here, but i'm giving you permission, because I know what I'm doing". It shouldn't be any different here.

Obviously, my example is absurd. It's hyperbole to demonstrate that logically the cause of the vulnerability: "ability to write arbitrary files" is true of the node core utilities, of which this library is an extension. `fs.writeFile()` isn't the operating system of decompress, it's in the same exact user space. It could be written to only write to the process cwd, with flags to allow an override.

From a technical perspective (what your program should be able to do to the filesystem, given sufficient privilege), this is not a security problem, at all.

But let me agree with you now. It might be, from a "social" perspective. In that a security exploit strategy can be to subvert the coder's social expectations of outcome. If we write the acceptance criteria of "an archive" such as (nevermind the different skillsets/expectations of the respective user bases of tar vs zip):

An Archive (the archive rules):
1. will only contain children resolving relative paths
2. no parent relative paths, and no absolute paths are allowed

If this set of assumptions is true for all "users" of decompress (historically this is more true for zip users than tar users), than this is both a bug, and also has the potential of being exploited (if and only if another security practice is subverted, such as needlessly giving write access to the filesystem in areas outside the domain of your application)

My problem with this notice is that:
1. the above assumptions are not (or have not been) universally true of tar users (of which I have been one for over 20 years)
2. given an alternative understanding of an archive (to be one that could very well have absolute and parent relative paths contained), there could have been legitimate and safe uses of such capability (just as there is legitimate and safe uses of `fs.writeFile()`)
3. the gravity is overstated, and the package authors don't deserve the negative social impact of the notice (I think we agree)
4. it is possible (both with command line tar and decompress package) to know what you are writing and to where, right now, with no patch, and to prevent writes to unexpected places.
5. the filesystem security model plays the same role in protecting `fs.writeFile()`, as it does `tar`, as it does decompress, and it's also subversive to a coder's understanding to assume this isn't true (or to ignore the fact).

**Comment by dl748** [comment]
> Obviously, my example is absurd. It's hyperbole to demonstrate that logically the cause of the vulnerability: "ability to write arbitrary files" is true of the node core utilities, of which this library is an extension. `fs.writeFile()` isn't the operating system of decompress, it's in the same exact user space. It could be written to only write to the process cwd, with flags to allow an override (that would be "secure" by default, sure it would break a lot of code, but...).

No, then it would impossible to write any utilities that DO add/update any system files, explicitly.  The utility is the only place to know whats permissible or not.  Also, it would prevent extraction into a temporary directory which is outside the cwd.  Requiring a process to change directories in order to modify files and directories would cause too many side effects.

> From a technical perspective (what your program should be able to do to the filesystem, given sufficient privilege), this is not a security problem, at all.

I agree, but what is expected from a security aspect is completely different than what its capable of.  For example, if you write a utility to add users to /etc/passwd and /etc/shadow, then if it has access, it should be able to.  But generalize code to extract from an archive, shouldn't arbitrarily delete all users from the system and change the root password because a third party archive sets it as a location.

> But let me agree with you now. It might be, from a "social" perspective. In that a security exploit strategy can be to subvert the coder's social expectations of outcome. If we write the acceptance criteria of "an archive" such as (nevermind the different skillsets/expectations of the respective user bases of tar vs zip):
> 
> An Archive (the archive rules):
> 
>     1. will only contain children resolving relative paths
> 
>     2. no parent relative paths, and no absolute paths are allowed
> 

Again, no, parent relative paths ARE allowed as long as they are contained within the extraction directory (think chroot) e.g. "test/../test.txt" is a perfectly valid file and should be extracted)

>     3. the gravity is overstated, and the package authors don't deserve the negative social impact of the notice (I think we agree)

Agreed, but authors should be responsive to security concerns and when they don't fix (or just close the project down).  It could also be positive too. I'm more likely to use third party, if they fix security issues in a timely manor (base on the complexity of the problem)

>     4. it is possible (both with command line tar and decompress package) to know what you are writing and to where, right now, with no patch, and to prevent writes to unexpected places.

Completely true, but that might not be the case for packages that automate things.

>     5. the filesystem security model plays the same role in protecting `fs.writeFile()`, as it does `tar`, as it does decompress, and it's also subversive to a coder's understanding to assume this isn't true (or to ignore the fact).

Of course, but to treat fs.writeFile() and tar as being similar is disingenuous.  writeFile modifies a single file and you have to specifically tell it the file to update.

Wherever the code is that writes the file, its THEIR responsibility for sanitizing the filename.  For example, JSZip doesn't have to worry about it because they give database back in a callback for the user of the utility to determine how they want to handle it.  In that case, its the responsibility of the person using JSZip to sanitize the files written to the disk.

if decompress were more like
```
decompress('my/archive', (fn, data) => {
  fs.writeFile(path.resolve(topath, fn), data)
})
```

Then I would say the problem does not lie with the decompress package but with whoever is using it.

> Programmers operating under this understand will already be wary of blind trust of the contents of an archive, and when input sanitization is necessary, they will certainly do so (using the filter option).

Its always going to be blind trust, unless the programmers that are using code to decompress are creating the archives themselves (which most likely is never the case).

**Comment by jdillick** [comment]
> > <snip> with flags to allow an override (that would be "secure" by default, sure it would break a lot of code, but...).
> 
> No, then it would impossible to write any utilities that DO add/update any system files, explicitly. The utility is the only place to know whats permissible or not. Also, it would prevent extraction into a temporary directory which is outside the cwd. Requiring a process to change directories in order to modify files and directories would cause too many side effects.

I did say "allow an override". ;)

> Again, no, parent relative paths ARE allowed as long as they are contained within the extraction directory (think chroot) e.g. "test/../test.txt" is a perfectly valid file and should be extracted)

Sure if that's the behavior every user expects (I think that's at least the convention the command line tools now uniformly default to), then it is at least a bug.

> Agreed, but authors should be responsive to security concerns and when they don't fix (or just close the project down). It could also be positive too. I'm more likely to use third party, if they fix security issues in a timely manor (base on the complexity of the problem)

This is easy to say, but we have a multitude of small packages, and often their utility makes them popular to use, but not necessary so popular for project participation. Authors pick things up and put them down, go on vacation, focus on other things for a time. Unfortunately, sometimes a good workaround / mitigation strategy is gonna get traction faster than a security notice that scares the shit out of everyone. Unfortunately, this is the source of many a fork, stale project, death of an otherwise good utility.

Also, big part of responding to these security notices is looking at them critically, not just accepting the claims themselves, assuming the actual risk or impact on real applications, not just hypotheticals, and at the potential misplace of responsibility. How mitigated is it naturally? Is this the right place to fix it? Should we look at how it is being applied? We aren't slaves to these opinions, and if ya'll are enchanted at the infallibility of these security groups, and their very fancy CVEs, you shouldn't be (respect the badge!) They are a blunt tool, run by people with a particular bent toward (often essential/useful) paranoia, but also often they lack all ability to see nuance, or to correctly interpret usage context, casting a wide net for tuna and sometimes killing dolphins in the process.

Please consider for a moment: Overzealous declarations of insecurity on small popular packages (in particular when the true risk is mitigated naturally, and the risk level is overblown LOW to HIGH) may have a higher toll than reward. I've been working with a devop engineer to deploy an application when one of these `npm audit` notices pops, and because it's a dependency of 20 other things, there is this long scary console pouring past my sys admins nose. Now I'm having an awkward conversation about why are we using node.js if it's so insecure, and he's telling his boss we should move to something more "rock solid" like Java. "Devs shouldn't be allowed to pick this unprofessional stack."

Don't get me wrong, I'm glad to know. But then I go back to my desk, and I'm seething because ordinary filesystem permissions mitigate the problem, and my files are on a completely different filesystem from the app and os, and the these are only build-time dev-dependencies to begin with.

> Of course, but to treat fs.writeFile() and tar as being similar is disingenuous. writeFile modifies a single file and you have to specifically tell it the file to update. I wouldn't expect webpack to write to system configuration files.

Yeah, I don't think disingenuous is the word, but I know what you are saying.

> 
> Wherever the code is that writes the file, its THEIR responsibility for sanitizing the filename.

Agree and disagree. The user of the software (application of the utility) knows better the desirable outcome (in the application) than lower in the stack, and has domain context the general purpose utility does not have. In this case we have a social concept (tar), which has an emergent convention of unpacking acyclically. In this case, I agree, the default behavior should reflect that.

> Its always going to be blind trust, unless the programmers that are using code to decompress are creating the archives themselves (which most likely is never the case).

Sure, I think it will always be human nature to trust that your own (the programmer's) understanding of the outcome will not be subverted. Taking advantage of the ability to create your own constraints over trusting the default behavior is still wise.

**Comment by jkroepke** [comment]
What about stop talking about if its a security issue or not and just follow other compress libraries and fix this issue? It's an issue and it should be fix.

Reference: https://snyk.io/research/zip-slip-vulnerability 

See also: 
* https://github.com/ZJONSSON/node-unzipper/pull/59
* https://pivotal.io/security/cve-2018-1261

**Comment by trptcolin** [comment]
AFAIK the maintainer hasn’t yet weighed in, but to be clear some folks have opened PRs: 

- https://github.com/kevva/decompress/pull/73
- https://github.com/kevva/decompress/pull/75

**Comment by jdillick** [comment]
Thanks to PR authors! Unfortunately, the last activity of @kevva was quite some long time ago. This might not even be on his radar.

Projects may have to abandon for another tool, [mitigate](https://github.com/kevva/decompress/issues/71#issuecomment-593046023) (if they don't mind the scarlet letter on their project in the interim), or someone can fork the repo (your project can do this themselves and use a git dependency in package.json for awhile), and or somebody publish a patched utility under a new package name. 🤷‍♂

```
# How you installed from patched git repo
npm install --save https://github.com/trptcolin/decompress.git#directory-traversal-patch
```

Maybe security@npmjs.com should let authors know how easy it is to mitigate...

**Comment by jkroepke** [comment]
If you look on the profile from @kevva you might be notice that the autor is active on github since the commit today to a private repository. 

Basically he is active, maybe someone should write him a mail. Maybe he is muting the whole project.

**Comment by trptcolin** [comment]
FWIW for any dependend projects - I wouldn't recommend depending on my git repo. I wouldn't trust myself to keep that branch around, particularly if the PR gets merged. No objections if somebody wants to maintain a (possibly-temporary) fork w/ my PR, but I'm not going to maintain it myself.

**Comment by jakejarvis** [comment]
@sindresorhus this is a long shot, but do you have any pull here? 😉

**Comment by adammcarth** [comment]
You can install your own patches for this package, but it still won't get rid of the `yarn audit` error. The security vulnerability [has been flagged](https://www.npmjs.com/advisories/1217) for _all_ versions of the package, regardless of whether it came from npm or your own repository. So CI pipelines will still fail.

In our case, the temporary solution we're using is to install our own fork (from the @trptcolin [patch](https://github.com/trptcolin/decompress/tree/directory-traversal-patch)), and then use the [improved-yarn-audit](https://www.npmjs.com/package/improved-yarn-audit) package:

```
yarn improved-yarn-audit --exclude 1217
```

We can now "safely" ignore this advisory because we've patched it with our own fork.

**Comment by nothingismagick** [comment]
Sent a mail to @kevva just now.

**Comment by jyulzz** [comment]
Thanks to everyone involved in this thread. I'm not nearly competent enough to understand the details of this issue, but I do see that it has been open for over a month, what (if any) resolution is in sight?

**Comment by morganchristiansson** [comment]
The maintainer is AWOL so noone here can merge PRs and make release. Last commit was 21 Aug 2017 - 3 years ago.

**Comment by jyulzz** [comment]
> The maintainer is AWOL so noone here can merge PRs and make release. Last commit was 21 Aug 2017 - 3 years ago.

Alright, thanks for checking/replying to me :)

**Comment by marechal-p** [comment]
I also think that allowing by default an archive to extract anything of the destination folder to be extremely fishy.

A workaround I used is to filter files via the options:

```ts
const absoluteDestPath = await fs.realpath(destPath);
await decompress(sourcePath, absoluteDestPath, {
    /**
     * Prevent zip-slip: https://snyk.io/research/zip-slip-vulnerability
     */
    filter(file: decompress.File): boolean {
        const expectedFilePath = path.join(absoluteDestPath, file.path);
        // If dest is not found in the expected path, it means file will be unpacked somewhere else.
        if (!expectedFilePath.startsWith(path.join(absoluteDestPath, path.sep))) {
            zipSlipFiles.add([file.path, expectedFilePath]);
            return false; // only skip the exploit files, maybe the rest is fine.
        } else {
            return true;
        }
    }
});
if (zipSlipFiles.size > 0) {
    console.error(`Detected a zip-slip exploit in archive: "${sourcePath}"`);
    for (const [relativePath, expectedPath] of zipSlipFiles) {
        console.error(` - File "${relativePath}" was going to write to: "${expectedPath}"`);
    }
    console.error('See: https://snyk.io/research/zip-slip-vulnerability');
}
```

I think it would be better to prevent this exploit by default, but allow to disable the check via the options (would anyone want to enable this back...)

**Comment by nothingismagick** [comment]
No reply from Kevva.

**Comment by jdillick** [comment]
> 
> Edit: I had not seen the comment from jdillick where he proposed a workaround too. I am not sure if just stripping leading `../` is a nice solution. When is it that you want to pack a file such as `../../foo.txt` and expect it to unpack at `dest/foo.txt`?

The issue is not (apparently) what you would want, but what you should be able to safely expect. The default behavior of the **packaging** of a parent relative path in GNU tar now is to treat `../../foo.txt` as `./foo.txt` in the produced tar file.

The safest route however would be simple decline any path that resolved to a parent.

e.g.

```
const decompress = require("decompress");
const path = require("path");
const assert = require("assert");

const allowedPath = (file, targetDir) => {
  // resolve relative path to target. e.g. file.path of a/../../b could actually be ../b
  const resolvedRelative = path.relative(
    targetDir,
    path.resolve(targetDir, file.path)
  );

  return !/^[..]{2}/.test(resolvedRelative);
};

assert.ok(allowedPath({ path: "./bar" }, "./foo"));
assert.ok(!allowedPath({ path: "../bar" }, "./foo"));
assert.ok(!allowedPath({ path: "../../bar" }, "./foo"));
assert.ok(!allowedPath({ path: "bar/../../baz" }, "./foo"));

const targetDir = path.resolve("./test-dir");

// silently filter out any path that resolves outside directory
decompress("./slip.tar.gz", targetDir, {
  filter: file => allowedPath(file, targetDir)
}).then(files => {
  files.forEach(file => console.log(file.path));
});
// no output
```

**Comment by sr1ch1** [comment]
Why don't you use @trptcolin fix? It addresses symlinks too.
see https://github.com/kevva/decompress/pull/73

**Comment by jdillick** [comment]
> Why don't you use @trptcolin fix? It addresses symlinks too.
> see #73

[Current version](https://www.npmjs.com/package/@atomic-reactor/decompress/v/4.2.2) won't allow creation of unsafe symlinks, or allow traversal of a symlink to create a file (without **followSymlink** option)

**Comment by sr1ch1** [comment]
Ah, I see. Thanks for clarification.

**Comment by hirvin-faria** [comment]
Hello, is there any recommended solution for this problem: "Arbitrary File Write"?

**Comment by jyulzz** [comment]
Hi @hirvin-faria, 

The long-term solution for this issue is for every package maker themselves to update their dependency to 'decompress' to another module that doesn't suffer from the same vulnerability.

In the meantime, if these errors bother you, you can manually substitute 'decompress' with '@atomic-reactor/decompress', a fork of 'decompress' where the vulnerability was corrected by @jdillick.

To do that :

1. Open your terminal
2. Change the directory to your project's folder
`cd (path to your project's folder) `
3. Install @atomic-reactor/decompress
`npm install --save @atomic-reactor/decompress`
4. Open the 'package-lock.json' file in your project's folder
`open package-lock.json`
5. Manually replace every instance where 'decompress' is listed as a dependency of another package by '@atomic-reactor/decompress' :  change `(...)"requires": { "decompress": "^4.0.0"(...)` to  (`...)"requires": {"@atomic-reactor/decompress": "^4.0.0"(...)`
6. You can also delete the part of package-lock.json where 'decompress' itself listed as a package, but if you don't know how to do that, you don't need to.

This is a quick fix to your issue. It might break in the future depending on how @atomic-reactor/decompress is maintained (no offense to its contributors), or on how packages that used to depend on 'decompress' will be updated themselves.

**Comment by jyulzz** [comment]
@hirvin-faria to stop getting those warnings when using packages that depend on 'decompress', these packages have to be fixed by their owners, contact them.
